out_dir : './experiments/synthetic_experiments/110620/'
dimensions : [4, 8, 12, 16, 20, 24, 28, 32, 36]
num_objectives : 40
num_samples : 1000
noise_variance : 0.01
factor_lengthscale : 2
gamma : 0.3
gp_hypers: 
    outputscale: 1.
n_max: 15
