name: gibo
channels:
  - defaults
dependencies:
  - numpy=1.19.2
  - matplotlib=3.3.2
  - python=3.8.5
  - nb_conda=2.2.1
  - pip=20.2.2
  - cython=0.29.21
  - pyyaml=5.3.1
  - mypy=0.812
  - pip:
    - botorch==0.3.1 
    - gpytorch==1.2.0
    - gym==0.9.3
    - mujoco-py==0.5.7
    - torch==1.6.0
    - torchvision==0.7.0
    - glfw==1.12.0
