method: rs  # (Augmented) random search.

out_dir: './experiments/rl_experiments/swimmer/rs/'

environment_name: Swimmer-v1
mlp:
    layers: [8,2]
    add_bias: True
    state_normalization: True
    manipulate_reward: 
        shift: 
        scale: 

trials: 3
# Either choose max_iterations or max_objective_calls unequal None.
max_iterations: 
max_objective_calls: 2000

optimizer_config:
    step_size: 0.02
    samples_per_iteration: 1
    exploration_noise: 0.01
    standard_deviation_scaling: True
    num_top_directions:
    param_args_ignore: [-1, -2]
    verbose: True
