method: gibo  # Bayesian gradient ascent.

out_dir: './experiments/rl_experiments/hopper/gibo_ablation_gradient_norm/'  # Directory for experiment results.

environment_name: Hopper-v1
mlp:
    layers: [11,3]
    add_bias: True
    discretize: 
    state_normalization: True
    manipulate_reward: 
        shift: 1
        scale: 1000

trials: 10
# Either choose max_iterations or max_objective_calls unequal None.
max_iterations:
max_objective_calls: 8000

optimizer_config: 
    max_samples_per_iteration: 32
    OptimizerTorch: sgd
    optimizer_torch_config: 
        lr: 1.
        weight_decay: 0.00001
    lr_schedular: {0: 0.6, 1000: 0.5, 2000: 0.3}
    Model: derivative_gp
    model_config:
        prior_mean: 0.
        ard_num_dims: dim_search_space  # If not None, each input dimension gets its own separate lengthscale.
        N_max: 128
        lengthscale_constraint: 
            constraint:
            kwargs:
        lengthscale_hyperprior: 
            prior: uniform
            kwargs: 
                a: 0.01
                b: 0.5
        outputscale_constraint:
            constraint: greather_than
            kwargs: 
                lower_bound: 0.001
        outputscale_hyperprior:
            prior: normal
            kwargs: 
                loc: 2.
                scale: 1.
        noise_constraint: 
            constraint:
            kwargs:
        noise_hyperprior:
            prior:
            kwargs:
    hyperparameter_config: 
        optimize_hyperparameters: True
        hypers:
            covar_module.base_kernel.lengthscale:
            covar_module.outputscale:
            likelihood.noise: .02
        no_noise_optimization: True
    optimize_acqf: bga
    optimize_acqf_config: 
        q: 1
        num_restarts: 5
        raw_samples: 64
    # Either choose bounds or delta unequal None.
    bounds: 
        lower_bound:
        upper_bound:
    delta: 0.2
    epsilon_diff_acq_value:
    generate_initial_data:
    standard_deviation_scaling: False
    normalize_gradient: False
    verbose: True
